name: CI

on:
  pull_request: {}
  # enable manual trigger - useful for debugging.
  workflow_dispatch: {}

jobs:
  build:
    name: build (poc - can be ignored)
    runs-on: ubuntu-latest
    container: jsii/superchain
    steps:
      - name: Check Out
        uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # fail the job if the cache is malfunctioning - we want to be aware of such problems cause it
        # will most likely cause dockerhub throttles.
        continue-on-error: false
      - name: Build
        run: /bin/bash ./build.sh && git diff-index --exit-code --ignore-space-at-eol --stat HEAD
